name: Snyk Security

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write # Erlaubt das Schreiben in die GitHub Security-Übersicht
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Offizielle Snyk Action für Node.js (führt automatisch npm install & Scan aus)
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-code.sarif

      # Lädt die generierte SARIF-Datei in deinen GitHub "Security"-Tab hoch
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        if: always() # Wird immer ausgeführt, selbst wenn Snyk Schwachstellen findet
        with:
          sarif_file: snyk-code.sarif
